resources:
  pipelines:
  - pipeline: SmartHotel
    project: DevOpsProject
    source: SmartHotel-CI
    trigger:
      branches:
        include:
        - releases/*
        - main
        exclude:
        - topic/*
      tags:
      - Verified
      - Signed
    jobs:
    - job: BuildAndDeploy
      displayName: 'Build and Deploy'
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        solution: '**/*.sln'
        buildConfiguration: 'Release'
      stages:
      - stage: Production
        displayName: 'Deploy to Production'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'releases/main'))
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Publish Artifact'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: true
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'CMP9785_Siddharth_26453965'
            appName: 'SmartAgriWebApp'
            package: '$(build.artifactstagingdirectory)/**/*.zip'
            appType: 'webApp'
      - stage: PreProduction
        displayName: 'Deploy to Pre-Production'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'releases/*'))
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Publish Artifact'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: true
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'CMP9785_Siddharth_26453965'
            appName: 'SmartAgriWebApp-Pre'
            package: '$(build.artifactstagingdirectory)/**/*.zip'
            appType: 'webApp'
