pool:
  vmImage: 'windows-latest'
trigger:
  - main
steps:
  - script: |
      npm init --yes
      sudo npm install
      sudo npm config set
    displayName: 'Initialise and install NPM packages'
  - script: |
      npm install
      npm test
    displayName: 'Run unit tests'
    continueOnError: 'true'
  - task: PublishTestResults@1
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/test-results.xml
  - script: |
     nyc --reporter=cobertura --reporter=html \
     npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results.xml
    displayName: 'Build code coverage report'
  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura # or JaCoCo
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
  - task: ArchiveFiles@2
    displayName: 'Archive sources'
    inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)
        includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
