pool:
  vmImage: 'windows-latest'
steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- script: |
    echo '{"name": "my-project", "version": "1.0.0"}' > package.json
    npm install
    npm test
  displayName: 'Run unit tests'
