pool:
  vmImage: 'windows-latest'
  trigger: 
    - main
steps:
  - script: |      
      npm init --yes
      sudo npm install
      sudo npm config set
    displayName: 'Initialise and install NPM packages'

  - script: |      
      npm install
      npm test
    displayName: 'Run unit tests'
    continueOnError: 'true'

  - task: CmdLine@2   
    inputs:
      script: 'npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results.xml'

  - task: PublishTestResults@1
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'

  - script: |
       npm install --save-dev jest jest-junit
       npm install --save-dev nyc
       nyc --reporter=html --reporter=cobertura node_modules/.bin/jest --ci --reporters=default --reporters=jest-junit
    displayName: 'Build code coverage report'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

  - task: ArchiveFiles@2
    displayName: 'Archive sources'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
