pool:
  vmImage: 'windows-latest'
trigger:
  - main
steps:
  - script: |
      npm init --yes
      sudo npm install
      sudo npm config set
    displayName: 'Initialise and install NPM packages'
  